server:
    port: 8081
zuul:
    routes:
        search:
            path: /api/**
            url: https://cloudsearch.apigw.ntruss.com/CloudSearch/real/v1
ncp:
    accessKey: { accessKey }
    secretKey: { secretKey }
spring:
    thymeleaf:
        cache: false
        check-template: true
        check-template-location: true
        enabled: true
        prefix: classpath:/static/
        suffix: .html
